config/routes.rb
Rails.application.routes.draw do
  root to: 'homepg#index'
  resources :homepg
  resources :secpg
  get '/games/:id', to: 'secpg#index', as: 'game'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepg_controller.rb
class HomepgController < ApplicationController

    def index
      @games = Game.limit(10).order(id: :desc)
    end
end

app/controllers/secpg_controller.rb
class SecpgController < ApplicationController

def index
    @games = Game.all.order(id: :desc)
  end

def show
  @games = Game.all
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepg_helper.rb
module HomepgHelper
end

app/helpers/secpg_helper.rb
module SecpgHelper
end

app/views/homepg/index.html.erb
<h1 style="background-color:DodgerBlue;color:White;border:2px solid Red;">100 Best Video Games Ever</h1>

<h3>Here's the top 10!!!</h3>
<% @games.each do |game| %>
  <p style="color:DodgerBlue; border:2px solid Violet;" >
  <%= game.title %>
  <%= game.release_date %>
  <%= game.rating %>
  <%= game.console %>
  </p>
<% end %>

<body>
  
<%= link_to 'Here is all 100!', secpg_path(@games) %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vgdb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/secpg/index.html.erb
<h1>100 Best Video Games Ever</h1>

<h3>Here's all 100</h3>
<% @games.each do |game| %>
  <p>
  <%= game.title %>
  <%= game.release_date %>
  <%= game.rating %>
  <%= game.console %>
  </p>
<% end %>